final List<Map<String, dynamic>> people = [
  {
    'id': '1',
    'fullname': 'Mary Jane',
    'gender': 'F',
    'age': '23',
    'country': 'Ukraine',
    'status': 'Doctor',
    'bio': 'Info about person',
    'friends': '123',
    'posts': '11',
    'scores': '123',
    'photo': 'assets/images/people/Woman_1.png',
    'followed': false,
    'isIam': false,
    'newbie': true
  },
  {
    'id': '2',
    'fullname': 'Peter Parker',
    'gender': 'M',
    'age': '18',
    'country': 'Germany',
    'status': 'Director of Football Club',
    'bio': 'Info about person',
    'friends': '121',
    'posts': '43',
    'scores': '22',
    'photo': 'assets/images/people/Man_1.png',
    'followed': false,
    'isIam': false,
    'newbie': true
  },
  {
    'id': '3',
    'fullname': 'Lana King',
    'gender': 'F',
    'age': '27',
    'country': 'Russia',
    'status': 'Waitress',
    'bio': 'Info about person',
    'friends': '65',
    'posts': '5',
    'scores': '10',
    'photo': 'assets/images/people/Woman_2.png',
    'followed': false,
    'isIam': false,
    'newbie': true
  },
  {
    'id': '4',
    'fullname': 'Samuel Bloom',
    'gender': 'M',
    'age': '22',
    'country': 'Azerbaijan',
    'status': 'Conductor',
    'bio': 'Info about person',
    'friends': '121',
    'posts': '43',
    'scores': '22',
    'photo': 'assets/images/people/Man_2.png',
    'followed': false,
    'isIam': false,
    'newbie': true
  },
  {
    'id': '5',
    'fullname': 'Jessica Alaba',
    'gender': 'F',
    'age': '43',
    'country': 'Ukraine',
    'status': 'Scientist',
    'bio': 'Info about person',
    'friends': '3',
    'posts': '17',
    'scores': '83',
    'photo': 'assets/images/people/Woman_3.png',
    'followed': false,
    'isIam': false,
    'newbie': true
  },
  {
    'id': '6',
    'fullname': 'Vasyl Koval',
    'gender': 'M',
    'age': '48',
    'country': 'Russia',
    'status': 'Bussinesman',
    'bio': 'Info about person',
    'friends': '98',
    'posts': '4',
    'scores': '9',
    'photo': 'assets/images/people/Man_3.png',
    'followed': false,
    'isIam': false,
    'newbie': true
  },
  {
    'id': '7',
    'fullname': 'Daniella Vasquez',
    'gender': 'F',
    'age': '29',
    'country': 'Spain',
    'status': 'Doctor',
    'bio': 'Info about person',
    'friends': '243',
    'posts': '662',
    'scores': '976',
    'photo': 'assets/images/people/Woman_4.png',
    'followed': false,
    'isIam': false,
    'newbie': true
  },
  {
    'id': '8',
    'fullname': 'Leo Gomez',
    'gender': 'M',
    'age': '33',
    'country': 'Argentina',
    'status': 'Policeman',
    'bio': 'Info about person',
    'friends': '121',
    'posts': '43',
    'scores': '22',
    'photo': 'assets/images/people/Man_4.png',
    'followed': false,
    'isIam': false,
    'newbie': false
  },
  {
    'id': '9',
    'fullname': 'Diana Muller',
    'gender': 'F',
    'age': '29',
    'country': 'Denmark',
    'status': 'Wine maker',
    'bio': 'Info about person',
    'friends': '13',
    'posts': '21',
    'scores': '3',
    'photo': 'assets/images/people/Woman_1.png',
    'followed': false,
    'isIam': false,
    'newbie': false
  },
  {
    'id': '10',
    'fullname': 'Yaroslav Abramovych',
    'gender': 'M',
    'age': '25',
    'country': 'France',
    'status': 'Director of Football Club',
    'bio': 'Info about person',
    'friends': '19',
    'posts': '432',
    'scores': '92',
    'photo': 'assets/images/people/Man_1.png',
    'followed': false,
    'isIam': false,
    'newbie': false
  },
  {
    'id': '11',
    'fullname': 'Amy Acker',
    'gender': 'F',
    'age': '39',
    'country': 'England',
    'status': 'Waitress',
    'bio': 'Info about person',
    'friends': '65',
    'posts': '5',
    'scores': '10',
    'photo': 'assets/images/people/Woman_2.png',
    'followed': false,
    'isIam': false,
    'newbie': false
  },
  {
    'id': '12',
    'fullname': 'Jason Dereck',
    'gender': 'M',
    'age': '44',
    'country': 'China',
    'status': 'Office manager',
    'bio': 'Info about person',
    'friends': '121',
    'posts': '43',
    'scores': '22',
    'photo': 'assets/images/people/Man_2.png',
    'followed': false,
    'isIam': false,
    'newbie': false
  },
  {
    'id': '13',
    'fullname': 'Kacy Jones',
    'gender': 'F',
    'age': '19',
    'country': 'Ukraine',
    'status': 'Scientist',
    'bio': 'Info about person',
    'friends': '52',
    'posts': '58',
    'scores': '88',
    'photo': 'assets/images/people/Woman_3.png',
    'followed': false,
    'isIam': false,
    'newbie': false
  },
  {
    'id': '14',
    'fullname': 'Ronald Van De Berg',
    'gender': 'M',
    'age': '25',
    'country': 'Netherlands',
    'status': 'Bussinesman',
    'bio': 'Info about person',
    'friends': '98',
    'posts': '4',
    'scores': '9',
    'photo': 'assets/images/people/Man_3.png',
    'followed': false,
    'isIam': false,
    'newbie': false
  },
  {
    'id': '15',
    'fullname': 'Phoebe Grace',
    'gender': 'F',
    'age': '31',
    'country': 'Belarus',
    'status': 'Air traffic controller',
    'bio': 'Info about person',
    'friends': '73',
    'posts': '52',
    'scores': '72',
    'photo': 'assets/images/people/Woman_4.png',
    'followed': false,
    'isIam': false,
    'newbie': false
  },
  {
    'id': '16',
    'fullname': 'Steven Henderson',
    'gender': 'M',
    'age': '37',
    'country': 'Scotland',
    'status': 'Policeman',
    'bio': 'Info about person',
    'friends': '121',
    'posts': '43',
    'scores': '22',
    'photo': 'assets/images/people/Man_4.png',
    'followed': false,
    'isIam': false,
    'newbie': false
  },
];
